"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Playfair_Display, Inter } from "next/font/google";
import { assets } from "@/Assets/assets";
import styles from "./RedesignedHome.module.css";

const playfair = Playfair_Display({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });
const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600"] });
const NAV = ["FİLM", "DİZİ", "EDEBİYAT", "SANAT", "DÜŞÜNCE", "DOSYA", "PODCAST", "VİDEO"];
const blogHref = (post) => post?._id ? `/blogs/${post._id}` : "#";
const img = (post) => post?.image || "/placeholder.jpg";
const category = (post) => post?.category || "YAZI";
function dateText(value){if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";return d.toLocaleDateString("tr-TR",{day:"numeric",month:"long",year:"numeric"});}

export default function RedesignedHome(){
 const [blogs,setBlogs]=useState([]); const [dark,setDark]=useState(false); const [today,setToday]=useState("");
 useEffect(()=>{setToday(new Date().toLocaleDateString("tr-TR",{day:"numeric",month:"long",year:"numeric",weekday:"long"}));fetch("/api/blog").then(r=>r.json()).then(data=>setBlogs(Array.isArray(data?.blogs)?data.blogs:[])).catch(()=>setBlogs([]));},[]);
 const posts=useMemo(()=>{if(!blogs.length)return[];const out=[];for(let i=0;i<16;i+=1)out.push(blogs[i%blogs.length]);return out;},[blogs]);
 const hero=posts[0],side=posts.slice(1,4),dossier=posts.slice(4,7),latest=posts.slice(7,11),picks=posts.slice(11,14),podcast=posts[14]||hero;
 return <div className={`${styles.page} ${dark?styles.dark:""} ${inter.className}`}>
 <div className={styles.shell}><header><div className={styles.utilityBar}><div className={styles.utilityLeft}><div className={styles.topLogoWrap}><Image src={assets.logo} alt="Aporetik logo" fill className={styles.logoImage} priority /></div><span className={styles.utilityDivider}/><span className={styles.date}>{today}</span></div><div className={styles.utilityRight}><button className={styles.utilityButton}>⌕ <span>Ara</span></button><button className={styles.utilityButton} onClick={()=>setDark(v=>!v)}>☼ <span>{dark?"Aydınlık Mod":"Karanlık Mod"}</span></button><button className={styles.memberButton}>Üye Ol</button><button className={styles.loginButton}>Giriş Yap</button></div></div><div className={styles.mastheadWrap}><Link href="/" className={`${styles.masthead} ${playfair.className}`}>aporetik<span>.</span></Link></div><nav className={styles.nav}>{NAV.map(item=><a href="#latest" key={item}>{item}</a>)}<button aria-label="Daha fazla">•••</button></nav></header>
 {hero?<main><section className={styles.heroSection}><article className={styles.heroCopy}><div className={styles.eyebrow}>ÖNE ÇIKAN YAZI <i/></div><h1 className={playfair.className}>{hero.title}</h1><p>{hero.description||"Aporetik'ten seçilmiş yazılar, incelemeler ve düşünce notları."}</p><Link href={blogHref(hero)} className={styles.readMore}>Yazıyı Oku <b>→</b></Link><div className={styles.pager}><strong>01</strong><span>02</span><span>03</span></div></article><Link href={blogHref(hero)} className={styles.heroImage}><Image src={img(hero)} alt={hero.title||"Öne çıkan yazı"} fill className={styles.cover} priority sizes="(max-width: 800px) 100vw, 44vw"/></Link><aside className={styles.sideStories}>{side.map((post,index)=><Link href={blogHref(post)} className={styles.sideStory} key={`${post._id}-${index}`}><div className={styles.sideThumb}><Image src={img(post)} alt="" fill className={styles.cover}/></div><div><span>{category(post)}</span><h3 className={playfair.className}>{post.title}</h3></div></Link>)}</aside></section><section className={styles.topicStrip}>{[["◉","Film İncelemeleri","Yeni çıkanlar, klasikler ve kült yapımlar"],["▤","Edebiyat Yazıları","Roman, öykü, şiir ve yazar dosyaları"],["✎","Düşünce Yazıları","Felsefe, toplum ve güncel tartışmalar"],["◖","Podcast & Video","Aporetik sesli ve görsel içerikler"]].map(([icon,title,text])=><div className={styles.topicItem} key={title}><div className={styles.topicIcon}>{icon}</div><div><h3 className={playfair.className}>{title}</h3><p>{text}</p></div></div>)}</section></main>:<div className={styles.loading}>Yazılar yükleniyor…</div>}</div>
 {hero&&<><section className={styles.dossierSection}><div className={styles.dossierInner}><div className={styles.dossierIntro}><div className={styles.goldEyebrow}>DOSYA <i/></div><h2 className={playfair.className}>Sinema: Gerçekliği<br/>Yeniden Kurmanın<br/>Biçimleri</h2><p>Sinema, yalnızca bir anlatı aracı değil; dünyaya bakışımızı değiştiren güçlü bir düşünme biçimidir.</p><button>Dosyayı Keşfet <span>→</span></button></div><div className={styles.dossierCards}>{dossier.map((post,index)=><Link href={blogHref(post)} className={styles.dossierCard} key={`${post._id}-d-${index}`}><Image src={img(post)} alt="" fill className={styles.cover}/><div className={styles.dossierShade}/><div className={styles.dossierText}><span>0{index+1} <i/></span><h3 className={playfair.className}>{post.title}</h3><p>{post.author||"Aporetik"}</p></div></Link>)}</div><button className={styles.circleArrow}>→</button></div></section>
 <div className={styles.shell}><section className={styles.latestArea} id="latest"><div className={styles.latestMain}><div className={styles.sectionHead}><h2 className={playfair.className}>Son Yazılar</h2><a href="#latest">Tüm Yazılar <span>→</span></a></div><div className={styles.latestGrid}>{latest.map((post,index)=><Link href={blogHref(post)} className={styles.latestCard} key={`${post._id}-l-${index}`}><div className={styles.latestImage}><Image src={img(post)} alt="" fill className={styles.cover}/></div><div className={styles.latestContent}><span>{category(post)}</span><h3 className={playfair.className}>{post.title}</h3><p>{post.author||"Aporetik"}</p><div><span>{dateText(post.date||post.createdAt)}</span><b>♡</b></div></div></Link>)}</div></div><aside className={styles.newsletter}><h2 className={playfair.className}>Aporetik Postası</h2><i/><p>Haftanın en iyi yazıları, özel içerikler ve yeni dosyalar e-posta kutunda.</p><input type="email" placeholder="E-posta adresiniz"/><button>Abone Ol</button><b>Bizi takip edin.</b><div className={styles.socials}>◎　𝕏　▶　●　◔</div></aside></section>
 <section className={styles.bottomEditorial}><div className={styles.editorsPick}><h2 className={playfair.className}>Editörün Seçkisi</h2>{picks.map((post,index)=><Link href={blogHref(post)} className={styles.pickRow} key={`${post._id}-p-${index}`}><div><Image src={img(post)} alt="" fill className={styles.cover}/></div><p><b className={playfair.className}>{post.title}</b><span>{category(post)}</span></p></Link>)}</div><div className={styles.podcast}><h2 className={playfair.className}>Aporetik Podcast</h2><div className={styles.podcastCard}>{podcast&&<Image src={img(podcast)} alt="" fill className={styles.podcastBg}/>}<div className={styles.podcastShade}/><div className={styles.podcastCopy}><span>Yeni Bölüm</span><h3 className={playfair.className}>Akira Kurosawa Üzerine<br/>Bir Sohbet</h3><p>Konuk: Ertan Yılmaz</p></div><div className={styles.audio}><button>▶</button><div>╴╵╷╶╵╷╴╵╷╶╵╷╴╵╷</div><b>42:18</b></div></div><button className={styles.outline}>Tüm Bölümleri Gör <span>→</span></button></div><div className={styles.support}><h2 className={playfair.className}>Aporetik’e Katıl</h2><p>Bağımsız ve nitelikli içeriğin sürdürülmesine destek ol.</p><button className={styles.outline}>Destek Ol <span>→</span></button><div className={styles.supportArt}><Image src="/reader-woman.webp" alt="Koltukta kitap okuyan kişi illüstrasyonu" fill className={styles.readerIllustration} sizes="(max-width: 640px) 90vw, 35vw"/></div></div></section>
 <footer className={styles.footer}><div className={styles.footerBrand}><div className={styles.footerLogoWrap}><Image src={assets.logo} alt="Aporetik" fill className={styles.logoImage}/></div><div><b className={playfair.className}>aporetik.</b><p>Düşünmeyi sevenler için.<br/>Bağımsız, nitelikli ve yavaş gazetecilik.</p></div></div><div><b>KURUMSAL</b><a>Hakkımızda</a><a>Yazarlar</a><a>Kariyer</a><a>İletişim</a></div><div><b>YARDIM</b><a>SSS</a><a>Gizlilik Politikası</a><a>Kullanım Şartları</a><a>Çerez Politikası</a></div><div><b>ARŞİV</b><a>Tüm Yazılar</a><a>Podcast Arşivi</a><a>Video Arşivi</a></div><p className={styles.copy}>© 2026 Aporetik. Tüm hakları saklıdır.<br/>Made with <span>♥</span> in İstanbul.</p></footer></div></>}</div>;
}
